In [1]:
import pandas as pd

In [2]:
df = pd.read_excel('../anketi/бабичи.xlsx')

In [3]:
df.head()

,Пол,Возраст,Семья,Другие родственники,Средовое окружение,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 72,Unnamed: 73,Unnamed: 74,Unnamed: 75,Unnamed: 76,Unnamed: 77,Unnamed: 78,Unnamed: 79,Unnamed: 80,Unnamed: 81
0,NaN,NaN,NaN,NaN,1,2,3,4,5.0,6,...,66,67.0,68,69.0,70,71,NaN,NaN,NaN,NaN
1,д,17.0,неполная (мать),Бабушка,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,м,17.0,неполная (мать),"Бабушка, дедушка, сестра (ы)",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,д,16.0,полная,-,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,15.0,неполная (мать),брат(я),NaN,иногда,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN